version: '3'

volumes:

    db-data-volume:
    wsgi-socket-volume:

services:

    base: &base_default
        build: .
        environment:
            DATABASE_URI: "postgresql://postgres:password@postgres/wx-api"
            APP_SETTINGS: "config.DevelopmentConfig"
            CHROME_DRIVER_PATH: "/opt/selenium/chromedriver-2.31"
        ports:
          - "5900:5900"
        volumes:
            - .:/wx-api
            - wsgi-socket-volume:/tmp/uwsgi
        depends_on:
            - "nginx"
            - "postgres"

    test:
        <<: *base_default
        environment:
            DATABASE_URI: 'sqlite://'
            APP_SETTINGS: "config.TestingConfig"
            PYTEST_ADDOPTS: '--flakes --pep8'

    nginx:
        build: nginx
        environment:
            - VIRTUAL_HOST=wx-api.test
        ports:
            - "7780:80"
        volumes:
            - ./static:/wx-api/static:ro
            - wsgi-socket-volume:/tmp/uwsgi

    postgres:
        build: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - db-data-volume:/var/lib/postgresql/data

    dnsmasq:
        image: andyshinn/dnsmasq:2.75
        command: "-A /test/127.0.0.1 --log-facility=-"
        ports:
            - "53:53/udp"
            - "53:53/tcp"
        depends_on:
            - nginx-proxy
        cap_add:
            - NET_ADMIN

    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
