version: '3'

volumes:

    db-data-volume:
    wsgi-socket-volume:

services:

    base:
        build: scraper
        environment:
            APP_SETTINGS: "config.DevelopmentConfig"
            DATABASE_URI: "postgresql://postgres:password@postgres/wx-api"
            CHROME_DRIVER_PATH: "/opt/selenium/chromedriver-2.31"
            SCRAPER_DATA_DIR: "data"
            WEBSITE_CREDENTIALS: "data/credentials.json"
            WEBSITE_URLS: "data/urls.json"
        ports:
          - "5900:5900"
        volumes:
            - .:/wx-api
        depends_on:
            - "postgres"
            - "amqp"

    api:
        build: app
        environment:
            APP_SETTINGS: "config.DevelopmentConfig"
            DATABASE_URI: "postgresql://postgres:password@postgres/wx-api"
        volumes:
            - .:/wx-api
            - wsgi-socket-volume:/tmp/uwsgi
        depends_on:
            - "base"
            - "nginx"
            - "postgres"
            - "amqp"

    nginx:
        build: nginx
        environment:
            - VIRTUAL_HOST=wx-api.test
        ports:
            - "7780:80"
        volumes:
            - ./static:/wx-api/static:ro
            - wsgi-socket-volume:/tmp/uwsgi

    postgres:
        build: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password
        volumes:
            - db-data-volume:/var/lib/postgresql/data

    dnsmasq:
        image: andyshinn/dnsmasq:2.75
        command: "-A /test/127.0.0.1 --log-facility=-"
        ports:
            - "53:53/udp"
            - "53:53/tcp"
        depends_on:
            - nginx-proxy
        cap_add:
            - NET_ADMIN

    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    amqp:
        image: rabbitmq:3.5-management
        ports:
            - "5672:5672"
            - "15672:15672"
        hostname: amqp
        environment:
            VIRTUAL_HOST: "amqp.test"
            VIRTUAL_PORT: 15672
